# flexdecoder - export CWB indexed corpora to VRT / JSONL / TEI XML
# Usage: make -f Makefile.flexdecoder
# Or: make -f Makefile.flexdecoder BINDIR=../Scripts

CXX = g++
CXXFLAGS = -std=c++17 -O2 -Wall -Wextra -I.

BINDIR = ../Scripts

FLEXDECODER_SRCS = flexdecoder.cpp flexdecoder_cwb.cpp flexdecoder_writers.cpp flexencoder_helpers.cpp
FLEXDECODER_OBJS = $(FLEXDECODER_SRCS:.cpp=.o)

flexdecoder: $(BINDIR)/flexdecoder

$(BINDIR)/flexdecoder: $(FLEXDECODER_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -f $(FLEXDECODER_OBJS) $(BINDIR)/flexdecoder

.PHONY: flexdecoder clean
